In [1]:
import numpy as np

In [2]:
np.arange(0, 60).reshape((3,2,5, 2))[2, ::2,1]

array([[42, 43]])

In [12]:
a = np.arange(10).reshape((2,-1))[:, ::-1]
a, a.item(9), a.item((1, -1)), a.shape, a.strides

(array([[4, 3, 2, 1, 0],
        [9, 8, 7, 6, 5]]),
 5,
 5,
 (2, 5),
 (20, -4))

In [4]:
np.array([[0]]).item()

0

In [5]:
type(True)

bool

In [11]:
for i in np.ndindex((0,)):
    print(i)

In [14]:
a = np.arange(3)
b = np.arange(6).reshape(2,3)

for x, y, z in np.nditer([a,b,None]):
    print(x, y, z)

0 0 0
1 1 1
2 2 2
0 3 3
1 4 4
2 5 5


In [19]:
x = np.array([[1], [2], [3]])
y = np.array([4, 5, 6])
b = np.broadcast(x, y)

list(b)

[(1, 4), (1, 5), (1, 6), (2, 4), (2, 5), (2, 6), (3, 4), (3, 5), (3, 6)]

In [75]:
x = np.array([1, 2, 3]).reshape((1,-1,1))
x.shape, x.strides, np.broadcast_to(x, (2,3,4)).strides

((1, 3, 1), (12, 4, 4), (0, 4, 0))

In [73]:
x

array([[[1],
        [2],
        [3]]])

In [78]:
np.broadcast_to(x, (2,3,4))

array([[[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]],

       [[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]]])

In [100]:
np.shape([1,2,3,[1,3]])

(4,)

In [128]:
a = [[1],[2],[3]]
b = np.asarray(a)
c = np.asarray(b)
c[0, 0]=5

In [129]:
a, b, c

([[1], [2], [3]],
 array([[5],
        [2],
        [3]]),
 array([[5],
        [2],
        [3]]))