In [1]:
import numpy as np

In [2]:
np.arange(0, 60).reshape((3,2,5, 2))[2, ::2,1]

array([[42, 43]])

In [12]:
a = np.arange(10).reshape((2,-1))[:, ::-1]
a, a.item(9), a.item((1, -1)), a.shape, a.strides

(array([[4, 3, 2, 1, 0],
        [9, 8, 7, 6, 5]]),
 5,
 5,
 (2, 5),
 (20, -4))

In [4]:
np.array([[0]]).item()

0

In [5]:
type(True)

bool

In [11]:
for i in np.ndindex((0,)):
    print(i)

In [14]:
a = np.arange(3)
b = np.arange(6).reshape(2,3)

for x, y, z in np.nditer([a,b,None]):
    print(x, y, z)

0 0 0
1 1 1
2 2 2
0 3 3
1 4 4
2 5 5


In [19]:
x = np.array([[1], [2], [3]])
y = np.array([4, 5, 6])
b = np.broadcast(x, y)

list(b)

[(1, 4), (1, 5), (1, 6), (2, 4), (2, 5), (2, 6), (3, 4), (3, 5), (3, 6)]

In [75]:
x = np.array([1, 2, 3]).reshape((1,-1,1))
x.shape, x.strides, np.broadcast_to(x, (2,3,4)).strides

((1, 3, 1), (12, 4, 4), (0, 4, 0))

In [73]:
x

array([[[1],
        [2],
        [3]]])

In [78]:
np.broadcast_to(x, (2,3,4))

array([[[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]],

       [[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]]])

In [100]:
np.shape([1,2,3,[1,3]])

(4,)

In [128]:
a = [[1],[2],[3]]
b = np.asarray(a)
c = np.asarray(b)
c[0, 0]=5

In [129]:
a, b, c

([[1], [2], [3]],
 array([[5],
        [2],
        [3]]),
 array([[5],
        [2],
        [3]]))

In [170]:
np.empty([]).shape

()

In [171]:
np.empty_like([1,2,3,[1,3]])

array([None, None, None, None], dtype=object)

In [177]:
np.ones([])

array(1.)

In [185]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = [[4], [7]]
np.copyto(A, B)
A

array([[4, 4, 4],
       [7, 7, 7]])

In [184]:
np.isscalar('[1,2]')

True

In [196]:
np.ndim(None), help(np.ndim)

Help on function ndim in module numpy:

ndim(a)
    Return the number of dimensions of an array.
    
    Parameters
    ----------
    a : array_like
        Input array.  If it is not already an ndarray, a conversion is
        attempted.
    
    Returns
    -------
    number_of_dimensions : int
        The number of dimensions in `a`.  Scalars are zero-dimensional.
    
    See Also
    --------
    ndarray.ndim : equivalent method
    shape : dimensions of array
    ndarray.shape : dimensions of array
    
    Examples
    --------
    >>> np.ndim([[1,2,3],[4,5,6]])
    2
    >>> np.ndim(np.array([[1,2,3],[4,5,6]]))
    2
    >>> np.ndim(1)
    0



(0, None)

In [223]:
a = np.array([[1, 2, 3], [4, 5, 6]])
np.copyto(a, 1, where=[[True], [False]]), a

(None,
 array([[1, 1, 1],
        [4, 5, 6]]))

In [226]:
help(np.eye)

Help on function eye in module numpy:

eye(N, M=None, k=0, dtype=<class 'float'>, order='C')
    Return a 2-D array with ones on the diagonal and zeros elsewhere.
    
    Parameters
    ----------
    N : int
      Number of rows in the output.
    M : int, optional
      Number of columns in the output. If None, defaults to `N`.
    k : int, optional
      Index of the diagonal: 0 (the default) refers to the main diagonal,
      a positive value refers to an upper diagonal, and a negative value
      to a lower diagonal.
    dtype : data-type, optional
      Data-type of the returned array.
    order : {'C', 'F'}, optional
        Whether the output should be stored in row-major (C-style) or
        column-major (Fortran-style) order in memory.
    
        .. versionadded:: 1.14.0
    
    Returns
    -------
    I : ndarray of shape (N,M)
      An array where all elements are equal to zero, except for the `k`-th
      diagonal, whose values are equal to one.
    
    See Also
    -

In [254]:
help(np.copyto)

Help on function copyto in module numpy:

copyto(...)
    copyto(dst, src, casting='same_kind', where=True)
    
    Copies values from one array to another, broadcasting as necessary.
    
    Raises a TypeError if the `casting` rule is violated, and if
    `where` is provided, it selects which elements to copy.
    
    .. versionadded:: 1.7.0
    
    Parameters
    ----------
    dst : ndarray
        The array into which values are copied.
    src : array_like
        The array from which values are copied.
    casting : {'no', 'equiv', 'safe', 'same_kind', 'unsafe'}, optional
        Controls what kind of data casting may occur when copying.
    
          * 'no' means the data types should not be cast at all.
          * 'equiv' means only byte-order changes are allowed.
          * 'safe' means only casts which can preserve values are allowed.
          * 'same_kind' means only safe casts or casts within a kind,
            like float64 to float32, are allowed.
          * 'uns

In [257]:
b= np.array([[0,1,2],[3,4,5]])
np.copyto(b[:,1],[-1,-2])
b

array([[ 0, -1,  2],
       [ 3, -2,  5]])

In [267]:
a=np.arange(10).reshape((2,5))
a[::-1,::-1].item(5)

4

In [269]:
np.array([[9,6], 3.1, 9]).shape

<ipython-input-269-a8fedbd342bb>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  np.array([[9,6], 3.1, 9]).shape


(3,)