In [1]:
import numpy as np

In [2]:
np.arange(0, 60).reshape((3,2,5, 2))[2, ::2,1]

array([[42, 43]])

In [3]:
a = np.arange(10).reshape((2,-1))[:, ::-1]
a, a.item(9), a.item((1, -1)), a.shape, a.strides

(array([[4, 3, 2, 1, 0],
        [9, 8, 7, 6, 5]]),
 5,
 5,
 (2, 5),
 (20, -4))

In [4]:
np.array([[0]]).item()

0

In [5]:
type(True)

bool

In [6]:
for i in np.ndindex((0,)):
    print(i)

In [7]:
a = np.arange(3)
b = np.arange(6).reshape(2,3)

for x, y, z in np.nditer([a,b,None]):
    print(x, y, z)

0 0 0
1 1 0
2 2 0
0 3 0
1 4 0
2 5 0


In [8]:
x = np.array([[1], [2], [3]])
y = np.array([4, 5, 6])
b = np.broadcast(x, y)

list(b)

[(1, 4), (1, 5), (1, 6), (2, 4), (2, 5), (2, 6), (3, 4), (3, 5), (3, 6)]

In [9]:
x = np.array([1, 2, 3]).reshape((1,-1,1))
x.shape, x.strides, np.broadcast_to(x, (2,3,4)).strides

((1, 3, 1), (12, 4, 4), (0, 4, 0))

In [10]:
x

array([[[1],
        [2],
        [3]]])

In [11]:
np.broadcast_to(x, (2,3,4))

array([[[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]],

       [[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]]])

In [12]:
np.shape([1,2,3,[1,3]])

C:\Users\cktto\.conda\envs\tf2\lib\site-packages\numpy\core\fromnumeric.py:2009: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  result = asarray(a).shape


(4,)

In [13]:
a = [[1],[2],[3]]
b = np.asarray(a)
c = np.asarray(b)
c[0, 0]=5

In [14]:
a, b, c

([[1], [2], [3]],
 array([[5],
        [2],
        [3]]),
 array([[5],
        [2],
        [3]]))

In [15]:
np.empty([]).shape

()

In [16]:
np.empty_like([1,2,3,[1,3]])

<__array_function__ internals>:180: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.


array([None, None, None, None], dtype=object)

In [17]:
np.ones([])

array(1.)

In [18]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = [[4], [7]]
np.copyto(A, B)
A

array([[4, 4, 4],
       [7, 7, 7]])

In [19]:
np.isscalar('[1,2]')

True

In [20]:
np.ndim(None), help(np.ndim)

Help on function ndim in module numpy:

ndim(a)
    Return the number of dimensions of an array.
    
    Parameters
    ----------
    a : array_like
        Input array.  If it is not already an ndarray, a conversion is
        attempted.
    
    Returns
    -------
    number_of_dimensions : int
        The number of dimensions in `a`.  Scalars are zero-dimensional.
    
    See Also
    --------
    ndarray.ndim : equivalent method
    shape : dimensions of array
    ndarray.shape : dimensions of array
    
    Examples
    --------
    >>> np.ndim([[1,2,3],[4,5,6]])
    2
    >>> np.ndim(np.array([[1,2,3],[4,5,6]]))
    2
    >>> np.ndim(1)
    0



(0, None)

In [21]:
a = np.array([[1, 2, 3], [4, 5, 6]])
np.copyto(a, 1, where=[[True], [False]]), a

(None,
 array([[1, 1, 1],
        [4, 5, 6]]))

In [22]:
help(np.eye)

Help on function eye in module numpy:

eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)
    Return a 2-D array with ones on the diagonal and zeros elsewhere.
    
    Parameters
    ----------
    N : int
      Number of rows in the output.
    M : int, optional
      Number of columns in the output. If None, defaults to `N`.
    k : int, optional
      Index of the diagonal: 0 (the default) refers to the main diagonal,
      a positive value refers to an upper diagonal, and a negative value
      to a lower diagonal.
    dtype : data-type, optional
      Data-type of the returned array.
    order : {'C', 'F'}, optional
        Whether the output should be stored in row-major (C-style) or
        column-major (Fortran-style) order in memory.
    
        .. versionadded:: 1.14.0
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__ar

In [23]:
help(np.copyto)

Help on function copyto in module numpy:

copyto(...)
    copyto(dst, src, casting='same_kind', where=True)
    
    Copies values from one array to another, broadcasting as necessary.
    
    Raises a TypeError if the `casting` rule is violated, and if
    `where` is provided, it selects which elements to copy.
    
    .. versionadded:: 1.7.0
    
    Parameters
    ----------
    dst : ndarray
        The array into which values are copied.
    src : array_like
        The array from which values are copied.
    casting : {'no', 'equiv', 'safe', 'same_kind', 'unsafe'}, optional
        Controls what kind of data casting may occur when copying.
    
          * 'no' means the data types should not be cast at all.
          * 'equiv' means only byte-order changes are allowed.
          * 'safe' means only casts which can preserve values are allowed.
          * 'same_kind' means only safe casts or casts within a kind,
            like float64 to float32, are allowed.
          * 'uns

In [24]:
b= np.array([[0,1,2],[3,4,5]])
np.copyto(b[:,1],[-1,-2])
b

array([[ 0, -1,  2],
       [ 3, -2,  5]])

In [25]:
a=np.arange(10).reshape((2,5))
a[::-1,::-1].item(5)

4

In [26]:
np.array([[9,6], 3.1, 9]).shape

C:\Users\cktto\AppData\Local\Temp\ipykernel_6436\1765726330.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[9,6], 3.1, 9]).shape


(3,)

In [37]:
a=np.arange(10)

a[:][:].base is a, np.asarray(a) is a

(True, True)

In [67]:
a=np.arange(10)[2:]
a.reshape((-1,2)).base is a

False

In [94]:
a = np.arange(2).reshape(1, -1)
c=a.flat
for item in c:
    for b in a.flat:
        print(b,c.index,c.coords)
    print(item,c.index,c.coords)

0 1 (0, 1)
1 1 (0, 1)
0 1 (0, 1)
0 2 (1, 0)
1 2 (1, 0)
1 2 (1, 0)


In [95]:
np.array([[0,1,2],[3,4,5]])[::-1].flat.copy()

array([3, 4, 5, 0, 1, 2])

In [102]:
np.array([[0,1,2],[3,4,5]])[::-1].flat[[0,-1]]

array([3, 2])

In [105]:
np.array([[1, 2, 3], [4, 5, 6]]).flat[[3,4,-1]]

array([4, 5, 6])

In [120]:
x=np.full((2,3),3)
x.flat[[1,-1]] = [[1],[2]]; x

array([[3, 1, 3],
       [3, 3, 2]])

In [135]:
x=np.full((2,3),-1)
x.flat = [7,8,9,10]
x

array([[ 7,  8,  9],
       [10,  7,  8]])

In [97]:
help(np.ndarray.flatten)

Help on method_descriptor:

flatten(...)
    a.flatten(order='C')
    
    Return a copy of the array collapsed into one dimension.
    
    Parameters
    ----------
    order : {'C', 'F', 'A', 'K'}, optional
        'C' means to flatten in row-major (C-style) order.
        'F' means to flatten in column-major (Fortran-
        style) order. 'A' means to flatten in column-major
        order if `a` is Fortran *contiguous* in memory,
        row-major order otherwise. 'K' means to flatten
        `a` in the order the elements occur in memory.
        The default is 'C'.
    
    Returns
    -------
    y : ndarray
        A copy of the input array, flattened to one dimension.
    
    See Also
    --------
    ravel : Return a flattened array.
    flat : A 1-D flat iterator over the array.
    
    Examples
    --------
    >>> a = np.array([[1,2], [3,4]])
    >>> a.flatten()
    array([1, 2, 3, 4])
    >>> a.flatten('F')
    array([1, 3, 2, 4])



In [175]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = x[:, 0:1]
np.ravel(y).base,  y.reshape(-1), y.reshape(-1).strides, y.strides, x.strides

(None, array([1, 4]), (12,), (12, 4), (12, 4))

In [189]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)
    
    Return evenly spaced values within a given interval.
    
    ``arange`` can be called with a varying number of positional arguments:
    
    * ``arange(stop)``: Values are generated within the half-open interval
      ``[0, stop)`` (in other words, the interval including `start` but
      excluding `stop`).
    * ``arange(start, stop)``: Values are generated within the half-open
      interval ``[start, stop)``.
    * ``arange(start, stop, step)`` Values are generated within the half-open
      interval ``[start, stop)``, with spacing between values given by
      ``step``.
    
    For integer arguments the function is roughly equivalent to the Python
    built-in :py:class:`range`, but returns an ndarray rather than a ``range``
    instance.
    
    When using a non-integer step, such as 0.1, it is often better to use
    `numpy.linspace`.
    
    S

In [188]:
np.arange(0,10,-1)

array([], dtype=int32)

In [193]:
np.arange(0, -10, -1)

array([ 0, -1, -2, -3, -4, -5, -6, -7, -8, -9])

In [195]:
np.linspace(2.0, 3.0)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [196]:
np.linspace(2.0, 3.0, num=5, endpoint=False, retstep=True)

(array([2. , 2.2, 2.4, 2.6, 2.8]), 0.2)

In [198]:
help(np.diagonal)

Help on function diagonal in module numpy:

diagonal(a, offset=0, axis1=0, axis2=1)
    Return specified diagonals.
    
    If `a` is 2-D, returns the diagonal of `a` with the given offset,
    i.e., the collection of elements of the form ``a[i, i+offset]``.  If
    `a` has more than two dimensions, then the axes specified by `axis1`
    and `axis2` are used to determine the 2-D sub-array whose diagonal is
    returned.  The shape of the resulting array can be determined by
    removing `axis1` and `axis2` and appending an index to the right equal
    to the size of the resulting diagonals.
    
    In versions of NumPy prior to 1.7, this function always returned a new,
    independent array containing a copy of the values in the diagonal.
    
    In NumPy 1.7 and 1.8, it continues to return a copy of the diagonal,
    but depending on this fact is deprecated. Writing to the resulting
    array continues to work as it used to, but a FutureWarning is issued.
    
    Starting in NumPy

In [263]:
help(np.take)

Help on function take in module numpy:

take(a, indices, axis=None, out=None, mode='raise')
    Take elements from an array along an axis.
    
    When axis is not None, this function does the same thing as "fancy"
    indexing (indexing arrays using arrays); however, it can be easier to use
    if you need elements along a given axis. A call such as
    ``np.take(arr, indices, axis=3)`` is equivalent to
    ``arr[:,:,:,indices,...]``.
    
    Explained without fancy indexing, this is equivalent to the following use
    of `ndindex`, which sets each of ``ii``, ``jj``, and ``kk`` to a tuple of
    indices::
    
        Ni, Nk = a.shape[:axis], a.shape[axis+1:]
        Nj = indices.shape
        for ii in ndindex(Ni):
            for jj in ndindex(Nj):
                for kk in ndindex(Nk):
                    out[ii + jj + kk] = a[ii + (indices[jj],) + kk]
    
    Parameters
    ----------
    a : array_like (Ni..., M, Nk...)
        The source array.
    indices : array_like (Nj...

In [209]:
a = np.array([[1, 2], [3, 4], [5, 6]])
np.take(a, [0, 2])

array([1, 3])

In [259]:
a = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
np.take(a, [[0, 1], [2, 3]])

array([[1, 2],
       [3, 4]])

In [336]:
a = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
np.take(a, [[0, 1], [2, 3]], axis=0)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [334]:
a = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
axis=1
indices = np.array([[[[0, 1],[0, 1]]]])
np.take(a, indices, axis=axis), np.take(a, indices, axis=axis).shape, a.shape[:axis] + indices.shape + a.shape[axis+1:]

(array([[[[[1, 2],
           [1, 2]]]],
 
 
 
        [[[[3, 4],
           [3, 4]]]],
 
 
 
        [[[[5, 6],
           [5, 6]]]],
 
 
 
        [[[[7, 8],
           [7, 8]]]]]),
 (4, 1, 1, 2, 2),
 (4, 1, 1, 2, 2))

In [331]:
c = np.empty(a.shape[:axis] + indices.shape + a.shape[axis+1:])
for ind in np.ndindex(indices.shape):
    print(ind)
c[:,0, 0, 0, 0] = a[:,indices[0, 0, 0, 0]]
c[:,0, 0, 0, 1] = a[:,indices[0, 0, 0, 1]]
c[:,0, 0, 1, 0] = a[:,indices[0, 0, 1, 0]]
c[:,0, 0, 1, 1] = a[:,indices[0, 0, 1, 1]]
c

(0, 0, 0, 0)
(0, 0, 0, 1)
(0, 0, 1, 0)
(0, 0, 1, 1)


array([[[[[1., 2.],
          [1., 2.]]]],



       [[[[3., 4.],
          [3., 4.]]]],



       [[[[5., 6.],
          [5., 6.]]]],



       [[[[7., 8.],
          [7., 8.]]]]])

In [342]:
np.c_[np.array([[1,2,3]]), 0, 0, np.array([[4,5,6]])]

array([[1, 2, 3, 0, 0, 4, 5, 6]])

In [338]:
np.c_[np.array([1,2,3]), np.array([4,5,6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [343]:
np.ix_([True, True], [2, 4])

(array([[0],
        [1]], dtype=int64),
 array([[2, 4]]))

In [344]:
np.ix_([True, True], [False, False, True, False, True])

(array([[0],
        [1]], dtype=int64),
 array([[2, 4]], dtype=int64))

In [345]:
np.indices((2, 3))

array([[[0, 0, 0],
        [1, 1, 1]],

       [[0, 1, 2],
        [0, 1, 2]]])

In [367]:
a = np.arange(3*4*5)
b = a.reshape((3, 4, 5))
a, np.swapaxes(b, 0, -1).base is a

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
        51, 52, 53, 54, 55, 56, 57, 58, 59]),
 True)

In [369]:
a = np.arange(3*4*5).reshape((3, 4, 5))
np.ascontiguousarray(a) is a

True

In [428]:
b = np.ones((3,4,5))[2,:,:]
np.ascontiguousarray(b) is b, b.strides, b.shape, b

(True,
 (40, 8),
 (4, 5),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [475]:
b = np.ones((3,))[1:2]
np.ascontiguousarray(b) is b, b.strides, b.shape, b, b.itemsize

(True, (8,), (1,), array([1.]), 8)

In [479]:
b.reshape(-1).base is b.base

True

In [495]:
x = np.array([[1,2,3],[1,2,3]])
y = np.swapaxes(x,0,1)
y, y.base is x

(array([[1, 1],
        [2, 2],
        [3, 3]]),
 True)

In [519]:
help(np.transpose)

Help on function transpose in module numpy:

transpose(a, axes=None)
    Reverse or permute the axes of an array; returns the modified array.
    
    For an array a with two axes, transpose(a) gives the matrix transpose.
    
    Refer to `numpy.ndarray.transpose` for full documentation.
    
    Parameters
    ----------
    a : array_like
        Input array.
    axes : tuple or list of ints, optional
        If specified, it must be a tuple or list which contains a permutation of
        [0,1,..,N-1] where N is the number of axes of a.  The i'th axis of the
        returned array will correspond to the axis numbered ``axes[i]`` of the
        input.  If not specified, defaults to ``range(a.ndim)[::-1]``, which
        reverses the order of the axes.
    
    Returns
    -------
    p : ndarray
        `a` with its axes permuted.  A view is returned whenever
        possible.
    
    See Also
    --------
    ndarray.transpose : Equivalent method
    moveaxis
    argsort
    
    N

In [518]:
a = np.array([[1, 2], [3, 4]])
np.transpose(a, np.array((0, -2))).base

ValueError: repeated axis in transpose

In [521]:
x = np.ones((1, 2, 3))
np.transpose(x, (1, 0, 2))

array([[[1., 1., 1.]],

       [[1., 1., 1.]]])

In [546]:
np.atleast_3d(1).strides

(4, 4, 4)

In [620]:
x = np.array([1])
y = x[0]
z = np.atleast_1d(y)
z[0] = -96
x, y, z, x.base is None, y.base is None, z.base is not y, z.base

(array([1]), 1, array([-96]), True, True, True, array(-96))

In [572]:
x = np.ones((1, 2, 3))

In [624]:
[array.strides for array in np.atleast_2d(1, [1, 2], [[1, 2]])]

[(4, 4), (0, 4), (8, 4)]

In [629]:
np.atleast_3d([1, 2]).strides

(0, 4, 0)

In [637]:
np.arange(12.0).reshape((4,3),1)

TypeError: 'tuple' object cannot be interpreted as an integer

In [700]:
x = np.array([1, 2, 3])
y = np.array([[4], [5], [6]])
y = np.array([[4], [5], [6]])
b = np.broadcast(x, y, z)
b.numiter, b.shape

(3, (3, 3))

In [666]:
i, j, k = b.iters
next(i), next(j), next(k)

(1, 4, -96)

In [693]:
x = np.array([1, 2, 3])
y = np.array([[4], [5], [6]])
b = np.broadcast(x, y)
row, col = b.iters
next(row), next(col)

(1, 4)

In [699]:
next(col)

6

In [709]:
x = np.array([1, 2])
y = np.expand_dims(x, axis=(0,1,2,3))
x.shape, y.shape

((2,), (1, 1, 1, 1, 2))

In [712]:
help(np.core.multiarray.normalize_axis_index)

Help on built-in function normalize_axis_index in module numpy.core._multiarray_umath:

normalize_axis_index(...)
    normalize_axis_index(axis, ndim, msg_prefix=None)
    
    Normalizes an axis index, `axis`, such that is a valid positive index into
    the shape of array with `ndim` dimensions. Raises an AxisError with an
    appropriate message if this is not possible.
    
    Used internally by all axis-checking logic.
    
    .. versionadded:: 1.13.0
    
    Parameters
    ----------
    axis : int
        The un-normalized index of the axis. Can be negative
    ndim : int
        The number of dimensions of the array that `axis` should be normalized
        against
    msg_prefix : str
        A prefix to put before the message, typically the name of the argument
    
    Returns
    -------
    normalized_axis : int
        The normalized axis index, such that `0 <= normalized_axis < ndim`
    
    Raises
    ------
    AxisError
        If the axis index is invalid, when `-

In [715]:
help(np.squeeze)

Help on function squeeze in module numpy:

squeeze(a, axis=None)
    Remove axes of length one from `a`.
    
    Parameters
    ----------
    a : array_like
        Input data.
    axis : None or int or tuple of ints, optional
        .. versionadded:: 1.7.0
    
        Selects a subset of the entries of length one in the
        shape. If an axis is selected with shape entry greater than
        one, an error is raised.
    
    Returns
    -------
    squeezed : ndarray
        The input array, but with all or a subset of the
        dimensions of length 1 removed. This is always `a` itself
        or a view into `a`. Note that if all axes are squeezed,
        the result is a 0d array and not a scalar.
    
    Raises
    ------
    ValueError
        If `axis` is not None, and an axis being squeezed is not of length 1
    
    See Also
    --------
    expand_dims : The inverse operation, adding entries of length one
    reshape : Insert, remove, and combine dimensions, and resi

In [750]:
np.core.multiarray.normalize_axis_index(-2,1)

AxisError: axis -2 is out of bounds for array of dimension 1

In [743]:
help(np.core.numeric.normalize_axis_tuple)

Help on function normalize_axis_tuple in module numpy.core.numeric:

normalize_axis_tuple(axis, ndim, argname=None, allow_duplicate=False)
    Normalizes an axis argument into a tuple of non-negative integer axes.
    
    This handles shorthands such as ``1`` and converts them to ``(1,)``,
    as well as performing the handling of negative indices covered by
    `normalize_axis_index`.
    
    By default, this forbids axes from being specified multiple times.
    
    Used internally by multi-axis-checking logic.
    
    .. versionadded:: 1.13.0
    
    Parameters
    ----------
    axis : int, iterable of int
        The un-normalized index or indices of the axis.
    ndim : int
        The number of dimensions of the array that `axis` should be normalized
        against.
    argname : str, optional
        A prefix to put before the error message, typically the name of the
        argument.
    allow_duplicate : bool, optional
        If False, the default, disallow an axis from

In [751]:
x = np.array([[[0], [1], [2]]])
np.squeeze(x, axis=(-1, -1))

ValueError: duplicate value in 'axis'

In [752]:
x = np.arange(20)
y = x.reshape((5, -1))
z = y[::-1]
a = np.ascontiguousarray(z)
b = a.reshape((5, 1, 1, -1))
b.reshape((5, -1)).base is a, b.reshape(-1).base is a, np.squeeze(b).base is a, x, y, z, np.squeeze(b)

(True,
 True,
 True,
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]]),
 array([[16, 17, 18, 19],
        [12, 13, 14, 15],
        [ 8,  9, 10, 11],
        [ 4,  5,  6,  7],
        [ 0,  1,  2,  3]]),
 array([[16, 17, 18, 19],
        [12, 13, 14, 15],
        [ 8,  9, 10, 11],
        [ 4,  5,  6,  7],
        [ 0,  1,  2,  3]]))

In [755]:
x = np.array(5)
y = np.ascontiguousarray(x)
x is y

False

In [767]:
help(np.nonzero)

Help on function nonzero in module numpy:

nonzero(a)
    Return the indices of the elements that are non-zero.
    
    Returns a tuple of arrays, one for each dimension of `a`,
    containing the indices of the non-zero elements in that
    dimension. The values in `a` are always tested and returned in
    row-major, C-style order.
    
    To group the indices by element, rather than dimension, use `argwhere`,
    which returns a row for each non-zero element.
    
    .. note::
    
       When called on a zero-d array or scalar, ``nonzero(a)`` is treated
       as ``nonzero(atleast_1d(a))``.
    
       .. deprecated:: 1.17.0
    
          Use `atleast_1d` explicitly if this behavior is deliberate.
    
    Parameters
    ----------
    a : array_like
        Input array.
    
    Returns
    -------
    tuple_of_arrays : tuple
        Indices of elements that are non-zero.
    
    See Also
    --------
    flatnonzero :
        Return indices that are non-zero in the flattened 

In [770]:
x = np.array([[3, 0, 0], [0, 4, 0], [5, 6, 0]])[..., None]
x, np.nonzero(x)

(array([[[3],
         [0],
         [0]],
 
        [[0],
         [4],
         [0]],
 
        [[5],
         [6],
         [0]]]),
 (array([0, 1, 2, 2], dtype=int64),
  array([0, 1, 0, 1], dtype=int64),
  array([0, 0, 0, 0], dtype=int64)))

In [773]:
x = np.array([[3, 0, 0], [0, 4, 0], [5, 6, 0]])
i, j = np.nonzero(x)
x[i, j], x[(i, j)]

(array([3, 4, 5, 6]), array([3, 4, 5, 6]))

In [777]:
np.nonzero(55)

(array([0], dtype=int64),)

In [778]:
np.argwhere(55)

array([], shape=(1, 0), dtype=int64)

In [793]:
a = np.array([[1, 2], [3, 4], [5, 6]])

np.compress([False, True, True], a, axis=0)

array([[3, 4],
       [5, 6]])

In [794]:
np.take(a, np.nonzero([False, True, True])[0], axis=0)

array([[3, 4],
       [5, 6]])

In [795]:
help(np.compress)

Help on function compress in module numpy:

compress(condition, a, axis=None, out=None)
    Return selected slices of an array along given axis.
    
    When working along a given axis, a slice along that axis is returned in
    `output` for each index where `condition` evaluates to True. When
    working on a 1-D array, `compress` is equivalent to `extract`.
    
    Parameters
    ----------
    condition : 1-D array of bools
        Array that selects which entries to return. If len(condition)
        is less than the size of `a` along the given axis, then output is
        truncated to the length of the condition array.
    a : array_like
        Array from which to extract a part.
    axis : int, optional
        Axis along which to take slices. If None (default), work on the
        flattened array.
    out : ndarray, optional
        Output array.  Its type is preserved and it must be of the right
        shape to hold the output.
    
    Returns
    -------
    compressed_arr

In [886]:
x = np.arange(40).reshape((5, -1)).copy()
y = x[None, :, None, None, ::3, None]
y.reshape(-1).base is x, np.ravel(y).base

(False, None)

In [884]:
y.shape, y.strides, y, x

((1, 5, 1, 1, 3, 1),
 (0, 32, 0, 0, 12, 0),
 array([[[[[[ 0],
            [ 3],
            [ 6]]]],
 
 
 
         [[[[ 8],
            [11],
            [14]]]],
 
 
 
         [[[[16],
            [19],
            [22]]]],
 
 
 
         [[[[24],
            [27],
            [30]]]],
 
 
 
         [[[[32],
            [35],
            [38]]]]]]),
 array([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31],
        [32, 33, 34, 35, 36, 37, 38, 39]]))

In [847]:
y.reshape(-1).strides

(4,)

In [ ]:
1 2 3 4 8

In [816]:
a = np.ones([3, 1, 5])[:,::3,:]
np.ascontiguousarray(a) is a

True

In [904]:
help(np.count_nonzero)

Help on function count_nonzero in module numpy:

count_nonzero(a, axis=None, *, keepdims=False)
    Counts the number of non-zero values in the array ``a``.
    
    The word "non-zero" is in reference to the Python 2.x
    built-in method ``__nonzero__()`` (renamed ``__bool__()``
    in Python 3.x) of Python objects that tests an object's
    "truthfulness". For example, any number is considered
    truthful if it is nonzero, whereas any string is considered
    truthful if it is not the empty string. Thus, this function
    (recursively) counts how many elements in ``a`` (and in
    sub-arrays thereof) have their ``__nonzero__()`` or ``__bool__()``
    method evaluated to ``True``.
    
    Parameters
    ----------
    a : array_like
        The array for which to count non-zeros.
    axis : int or tuple, optional
        Axis or tuple of axes along which to count non-zeros.
        Default is None, meaning that non-zeros will be counted
        along a flattened version of ``a``.
 

In [920]:
a = np.ones((2, 3, 4, 5))
np.count_nonzero(a, (0, -1))

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]], dtype=int64)

In [910]:
a = np.ones((2, 3, 4, 5))
np.count_nonzero(a, 0)

array([[[2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2]],

       [[2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2]],

       [[2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2]]], dtype=int64)

In [911]:
a = np.ones((2, 3, 4, 5))
np.count_nonzero(a, 1)

array([[[3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3]],

       [[3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3]]], dtype=int64)

In [912]:
a = np.ones((2, 3, 4, 5))
np.count_nonzero(a)

120

In [913]:
a = np.ones((2, 3, 4, 5))
np.count_nonzero(a, -1)

array([[[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]],

       [[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]]], dtype=int64)

In [926]:
x = np.ones((4, 10), dtype=bool)[::2, :]
x.strides, x.shape, x.size

((20, 1), (2, 10), 20)

In [929]:
np.arange(10).reshape([5, -1]) * np.arange(10, 20).reshape([5, -1])

array([[  0,  11],
       [ 24,  39],
       [ 56,  75],
       [ 96, 119],
       [144, 171]])

In [934]:
np.sin(np.arange(30).reshape(2, 5, 1, -1, 1)).tolist()

[[[[[0.0], [0.8414709848078965], [0.9092974268256817]]],
  [[[0.1411200080598672], [-0.7568024953079282], [-0.9589242746631385]]],
  [[[-0.27941549819892586], [0.6569865987187891], [0.9893582466233818]]],
  [[[0.4121184852417566], [-0.5440211108893698], [-0.9999902065507035]]],
  [[[-0.5365729180004349], [0.4201670368266409], [0.9906073556948704]]]],
 [[[[0.6502878401571168], [-0.2879033166650653], [-0.9613974918795568]]],
  [[[-0.7509872467716762], [0.14987720966295234], [0.9129452507276277]]],
  [[[0.8366556385360561], [-0.008851309290403876], [-0.8462204041751706]]],
  [[[-0.9055783620066238], [-0.13235175009777303], [0.7625584504796027]]],
  [[[0.956375928404503], [0.27090578830786904], [-0.6636338842129675]]]]]

In [936]:
a=np.array([[[[[0],[0.8414709848078965],[0.9092974268256817]]],[[[0.1411200080598672],[-0.7568024953079282],[-0.9589242746631385]]],[[[-0.27941549819892586],[0.6569865987187891],[0.9893582466233818]]],[[[0.4121184852417566],[-0.5440211108893698],[-0.9999902065507035]]],[[[-0.5365729180004349],[0.4201670368266409],[0.9906073556948704]]]],[[[[0.6502878401571168],[-0.2879033166650653],[-0.9613974918795568]]],[[[-0.7509872467716762],[0.14987720966295234],[0.9129452507276277]]],[[[0.8366556385360561],[-0.008851309290403876],[-0.8462204041751706]]],[[[-0.9055783620066238],[-0.13235175009777303],[0.7625584504796028]]],[[[0.956375928404503],[0.27090578830786904],[-0.6636338842129675]]]]])
b=np.array([[[[[0.0], [0.8414709848078965], [0.9092974268256817]]],
  [[[0.1411200080598672], [-0.7568024953079282], [-0.9589242746631385]]],
  [[[-0.27941549819892586], [0.6569865987187891], [0.9893582466233818]]],
  [[[0.4121184852417566], [-0.5440211108893698], [-0.9999902065507035]]],
  [[[-0.5365729180004349], [0.4201670368266409], [0.9906073556948704]]]],
 [[[[0.6502878401571168], [-0.2879033166650653], [-0.9613974918795568]]],
  [[[-0.7509872467716762], [0.14987720966295234], [0.9129452507276277]]],
  [[[0.8366556385360561], [-0.008851309290403876], [-0.8462204041751706]]],
  [[[-0.9055783620066238], [-0.13235175009777303], [0.7625584504796027]]],
  [[[0.956375928404503], [0.27090578830786904], [-0.6636338842129675]]]]])

a-b

array([[[[[0.00000000e+00],
          [0.00000000e+00],
          [0.00000000e+00]]],


        [[[0.00000000e+00],
          [0.00000000e+00],
          [0.00000000e+00]]],


        [[[0.00000000e+00],
          [0.00000000e+00],
          [0.00000000e+00]]],


        [[[0.00000000e+00],
          [0.00000000e+00],
          [0.00000000e+00]]],


        [[[0.00000000e+00],
          [0.00000000e+00],
          [0.00000000e+00]]]],



       [[[[0.00000000e+00],
          [0.00000000e+00],
          [0.00000000e+00]]],


        [[[0.00000000e+00],
          [0.00000000e+00],
          [0.00000000e+00]]],


        [[[0.00000000e+00],
          [0.00000000e+00],
          [0.00000000e+00]]],


        [[[0.00000000e+00],
          [0.00000000e+00],
          [1.11022302e-16]]],


        [[[0.00000000e+00],
          [0.00000000e+00],
          [0.00000000e+00]]]]])

In [948]:
a = np.arange(100).reshape(5, -1, 1)[::-2, 2:7]

np.sum(a, (0, -1))

array([126, 129, 132, 135, 138])

In [950]:
(1,2,3) == (1,2,3)

True

In [951]:
help(np.mod)

Help on ufunc:

remainder = <ufunc 'remainder'>
    remainder(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Returns the element-wise remainder of division.
    
    Computes the remainder complementary to the `floor_divide` function.  It is
    equivalent to the Python modulus operator``x1 % x2`` and has the same sign
    as the divisor `x2`. The MATLAB function equivalent to ``np.remainder``
    is ``mod``.
    
    .. warning::
    
        This should not be confused with:
    
        * Python 3.7's `math.remainder` and C's ``remainder``, which
          computes the IEEE remainder, which are the complement to
          ``round(x1 / x2)``.
        * The MATLAB ``rem`` function and or the C ``%`` operator which is the
          complement to ``int(x1 / x2)``.
    
    Parameters
    ----------
    x1 : array_like
        Dividend array.
    x2 : array_like
        Divisor array.
        If ``x1.shape != x2.s

In [954]:
np.isscalar(1)

True

In [960]:
help(np.pi)

Help on float object:

class float(object)
 |  float(x=0, /)
 |  
 |  Convert a string or number to a floating point number, if possible.
 |  
 |  Methods defined here:
 |  
 |  __abs__(self, /)
 |      abs(self)
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __bool__(self, /)
 |      True if self else False
 |  
 |  __ceil__(self, /)
 |      Return the ceiling as an Integral.
 |  
 |  __divmod__(self, value, /)
 |      Return divmod(self, value).
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __float__(self, /)
 |      float(self)
 |  
 |  __floor__(self, /)
 |      Return the floor as an Integral.
 |  
 |  __floordiv__(self, value, /)
 |      Return self//value.
 |  
 |  __format__(self, format_spec, /)
 |      Formats the float according to format_spec.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getnewargs__(self, /)
 |  
 |  __gt__(sel

In [961]:
np.e

2.718281828459045

In [962]:
np.arccos([1, -1]).tolist()

[0.0, 3.141592653589793]

In [963]:
help(np.pow)

AttributeError: module 'numpy' has no attribute 'pow'

In [971]:
phase = np.linspace(0, np.pi, num=10)
phase[3:] += np.pi
phase = phase.reshape(5, -1)
phase, np.unwrap(phase, axis=0), np.unwrap(phase, axis=-1)

(array([[0.        , 0.34906585],
        [0.6981317 , 4.1887902 ],
        [4.53785606, 4.88692191],
        [5.23598776, 5.58505361],
        [5.93411946, 6.28318531]]),
 array([[ 0.        ,  0.34906585],
        [ 0.6981317 , -2.0943951 ],
        [-1.74532925, -1.3962634 ],
        [-1.04719755, -0.6981317 ],
        [-0.34906585,  0.        ]]),
 array([[ 0.        ,  0.34906585],
        [ 0.6981317 , -2.0943951 ],
        [ 4.53785606,  4.88692191],
        [ 5.23598776,  5.58505361],
        [ 5.93411946,  6.28318531]]))

In [972]:
np.mod(np.linspace(0 ,720, 19), 360) - 180

array([-180., -140., -100.,  -60.,  -20.,   20.,   60.,  100.,  140.,
       -180., -140., -100.,  -60.,  -20.,   20.,   60.,  100.,  140.,
       -180.])

In [973]:
phase_deg = np.mod(np.linspace(0 ,720, 19), 360) - 180
np.unwrap(phase_deg, period=360)

array([-180., -140., -100.,  -60.,  -20.,   20.,   60.,  100.,  140.,
        180.,  220.,  260.,  300.,  340.,  380.,  420.,  460.,  500.,
        540.])

In [975]:
help(np.radians)

Help on ufunc:

radians = <ufunc 'radians'>
    radians(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Convert angles from degrees to radians.
    
    Parameters
    ----------
    x : array_like
        Input array in degrees.
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retain its original value.
        Note that if an uninitialized `out` array is created via the default
        ``

In [978]:
np.around([-5, -15, -25, -35, -45], decimals=-1)

array([  0, -20, -20, -40, -40])

In [979]:
np.NINF

-inf

In [980]:
help(np.diff)

Help on function diff in module numpy:

diff(a, n=1, axis=-1, prepend=<no value>, append=<no value>)
    Calculate the n-th discrete difference along the given axis.
    
    The first difference is given by ``out[i] = a[i+1] - a[i]`` along
    the given axis, higher differences are calculated by using `diff`
    recursively.
    
    Parameters
    ----------
    a : array_like
        Input array
    n : int, optional
        The number of times values are differenced. If zero, the input
        is returned as-is.
    axis : int, optional
        The axis along which the difference is taken, default is the
        last axis.
    prepend, append : array_like, optional
        Values to prepend or append to `a` along axis prior to
        performing the difference.  Scalar values are expanded to
        arrays with length 1 in the direction of axis and the shape
        of the input array in along all other axes.  Otherwise the
        dimension and shape must match `a` except along ax

In [984]:
a = np.ones((3,))
np.ravel(a).base is a, a.flatten().base

(True, None)

In [987]:
np.concatenate([[1, 2], [[1], [2]]])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [994]:
np.concatenate([[[1,9], [2,2]], [[1,9], [2,2]], [[1], [2]]])

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 2 has size 1

In [989]:
np.concatenate([[[1], [2]], [[1], [2]]])

array([[1],
       [2],
       [1],
       [2]])

In [993]:
np.concatenate([1])

ValueError: zero-dimensional arrays cannot be concatenated

In [997]:
np.concatenate([1, [[1,9], [2,2]], 0])

ValueError: zero-dimensional arrays cannot be concatenated

In [1001]:
np.concatenate([[[1], [2]], [[1], [2]]], out=np.empty((2,5)))

ValueError: Output array is the wrong shape

In [1023]:
np.array([1,2,3,4,5])[::-2].reshape(-1)

array([5, 3, 1])

In [1022]:
a=np.array(1)
a.reshape([1])

array([1])

In [1025]:
a=np.ones((1,))
np.concatenate([a]) is a

False

In [1028]:
np.ediff1d( np.array([1, 2, 4, 7, 0]), to_begin=-99, to_end=np.array([88, 99]))

array([-99,   1,   2,   3,  -7,  88,  99])

In [1030]:
a=np.ones((1,))
a.reshape(-1) is a

False

In [1033]:
a=np.array([1,2,3])
b = a[..., 0]
b.itemset(0, -99)
a

array([-99,   2,   3])

In [1049]:
x=np.array([[1]])
x[...,0, 0].base

array([[1]])

In [1050]:
x = np.array([[1,2,3], [4,5,6]])
y = np.array([[4,5,6], [1,2,3]])
np.cross(x, y, axisc=0)

array([[-3,  3],
       [ 6, -6],
       [-3,  3]])